### ISSUE TITLE
Add editor scripts to bundle

### ISSUE THREAD

**Issue by subsoap** [JustAPotota/dae2collision#1]
There is an example of an editor script in the readme but no actual editor scripts usable when adding this as a dependency which is probably what most users would expect.

**Comment by JustAPotota** [comment]
The project is set up that way since almost every game requires its own collision object settings, which means making a custom editor script. I don't know of a way to make it more "batteries included" while also keeping it customizable. If I include an editor script with "standard" settings in the library folder, then anyone who makes their own will be stuck with an annoying duplicate menu entry.

**Comment by subsoap** [comment]
Just have one that is set to the default settings. "Generate Collision - Default"

**Comment by JustAPotota** [comment]
Added in [v1.1.0](https://github.com/JustAPotota/dae2collision/releases/tag/v1.1.0).
